version: '3'
services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: Gleb
      MINIO_SECRET_KEY: Az100Az.
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: CarInventoryDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  api:
    container_name: main
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "0:8081"
      - "0:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CarInventoryDB;Username=postgres;Password=1234
    depends_on:
      - db

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: CarGuideDDD.TelegramBot/Dockerfile

  mail:
    container_name: mail
    build:
      context: .
      dockerfile: CarGuideDDD.MailService/Dockerfile
    ports:
      - "0:8084"
      - "0:8085"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  minio-data:

