services:  
    db:    
        image: postgres:latest
        environment:        
            POSTGRES_DB: CarInventoryDB
            POSTGRES_USER: postgres        
            POSTGRES_PASSWORD: 1234
        ports:        
         - "5432:5432"
    api:  
        build:
          context: .      
          dockerfile: API/Dockerfile
        ports:
            - "8081:7162"
            - "8080:7163"     
        environment:
          - ASPNETCORE_ENVIRONMENT=Development      
          - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CarInventoryDB;Username=postgres;Password=1234
        depends_on:      
            - db
    bot:
        build:
            context: .
            dockerfile: CarGuideDDD.TelegramBot/Dockerfile
        ports:
            - "8082:5000"
            - "8083:5001"
    mail:
        build:
            context: .
            dockerfile: CarGuideDDD.MailService/Dockerfile
        ports:
            - "8084:8084"
            - "8085:8085"
    
    
